### ISSUE TITLE
Links don't work in production (after build)

### ISSUE THREAD

**Issue by breezykermo** [gridsome/gridsome-starter-default#2]
The links in [Index.vue](src/pages/Index.vue) work nicely in development, but when I try to build to a static site, the links don't work. They update the path in the browser, but they don't seem to update the HTML content.

Does anyone have any idea why this would be the case?

**Comment by hjvedvik** [comment]
I have experienced that issue myself. Vue somehow fails to re-render after a mismatch in the server-side rendered markup. You can try to run the HTML source through [W3C Validator](https://validator.w3.org/) to find any invalid markup. Read more about what can cause the issue [here](https://ssr.vuejs.org/guide/hydration.html#hydration-caveats). But I will investigate why the app is not responding after the re-render.

**Comment by breezykermo** [comment]
The markup all seems to be rendering correctly, and the links work fine in development. It's just when I try to build it into a static site that there is an issue; which would suggest that it's something to do with Gridsome's transformation of the GraphQL queries (in `gridsome develop`) to JS chunks (created during `gridsome build`).

I'm using a lot of inline HTML in the .md files--could this be what is causing the problem?

**Comment by breezykermo** [comment]
The HTML source through the validator link above has no issues.

I did a little more profiling here. When a link is clicked in the SSR-generated code, two JS chunks area retrieved, the first of which seems to have JS with the logic to saturate the state of the application with the new route, and the second of which has the new route's information to add to the `window.wepbackJsonp` (presumably a part of Vue SSR magic).

The retrieval of these two chunks throws the following error in the _main JS file_'s body:
![screen shot 2018-11-07 at 10 31 02](https://user-images.githubusercontent.com/16495856/48126120-48cac000-e278-11e8-83e0-a777fd237aff.png)

Presumably this is the point at which the link goes wrong. The JS from those two chunks succeed in pushing the new route to the browser history, but then trip up somewhere trying to saturate the application state.

**Comment by hjvedvik** [comment]
I've investigated this a bit further, and I think it is the `noscript` tags from the `g-image` component which is causing the hydration failure. Try to remove all `g-image` components on the failing page and see if it helps. At least, I am getting the same error message here and I'm working on a fix now :)

**Comment by breezykermo** [comment]
Removing `g-image` tags does indeed make links work in production, thank you! Looking forward to the fix upstream, thanks for your great work.

**Comment by breezykermo** [comment]
@tomtev, is this fixed in the most recent version, even with `g-image`?

**Comment by oliverdozsa** [comment]
I think it's still not working on 0.5.4. What's the alternative instead of g-image?

**Comment by oliverdozsa** [comment]
> I think it's still not working on 0.5.4. What's the alternative instead of g-image?

My mistake, there were some problems on my side. It's all working!

**Comment by narration-sd** [comment]
I ran into this over the weekend of putting together a product release site due to Vuetify, which silently inserts html elements unexpectedly in some cases, as the list elements that go with Navigation Drawers.

Result: as with everyone else, my site worked fine in dev, and refused menus and routing when built and live. So, as anyone, I searched until I found this and one or two other useful links, and fixed the problem. The  tldr: is ,you don't have to use their List elements. Not that this is doc'd either.

I understand the nature of the breakage, but haven't time to dig around some solution if there is one. I don't see the same thing in work with Gatsby, but anyway that's a different basis and architecture. 

It is going to be a problem pretty predictably for Gridsome, one would think ref for example https://github.com/gridsome/gridsome/issues/269#issuecomment-471375422, if I have nothing but compliments for how fine Gridsome and attitude of its developers appear to be.

I would think for the moment that a highlighted advice to run a site through validator.w3.org immediately after it's built would be very helpful. Yes, that's intimidating for many, and advice on what to do is typically rude and deliberately vague, but the key is that you don't have to fix everything. 

Broken html elements due to unexpected insertions is one, for which certainly better words can be found, and it seems that for this 'just built' moment of the doc, a short list can probably be made.

Or some kind of a trapper app, which exercises a site looking for actual Gridsome losing its way? 

Maybe that's a kind of solution to be looking for. And quite possibly that could be a webpack'd item to run, so under a simple npm run tryme sort of public-simple command??

Enough, am sure, but  trying to be as helpful as I can...Velbekommen!

**Comment by LukeXF** [comment]
Is this issue resolved? I'm still getting them on the production version of my website

**Comment by codeserk** [comment]
So, does that mean `g-image` should not be used in production? I'm confused now :(

**Comment by sushantagithub** [comment]
Same issue I found

**Comment by RyanCwynar** [comment]
I've been running into this issue.

**Comment by supertommy** [comment]
I experienced a similar problem but `g-image` was not the cause. It was related to the [Vue hydration caveat](https://ssr.vuejs.org/guide/hydration.html#hydration-caveats) mentioned by @hjvedvik 

In my case, I had an `h2` within an `h1` and apparently that is invalid markup :) There were other errors from the [W3C Validator](https://validator.w3.org/) but that was the one that mattered.

This problem manifested for me as going from the page with invalid markup to another page. So the problem was the source page I tried to click a link from and not the page that appeared to not load.

**Comment by toybreaker** [comment]
I am running into this same issue in this:
[magicgreensome.netlify.app](https://magicgreensome.netlify.app/)
anyone can indicate the way to solve the issue,
it will be definitely prevent me to use Gridsome in any of my projects.
Any help will be much appreciated, since the whole whole framework looks promising, thanks in advance...

**Comment by DesignedByNino** [comment]
I had this error for a build one night, and it was related to my mistake of accidentally inserting a ``` <button> ``` tag inside <br/> a ``` <g-link> ``` element. <br />

 I also found errors about ``` <img /> ``` requiring an ``` alt="image text" ``` attribute, so if you get it, first check all ``` <a> Links </a> ``` , ``` <h1> Headings </h1> ``` and ``` <img /> ``` <br />

After cleaning up those mistakes, the build runs smooth and all works fine!
